# Generated by Django 4.2.2 on 2023-12-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=100, null=True)),
                ('idService', models.IntegerField(null=True)),
                ('idOrgao', models.IntegerField(null=True)),
                ('cpf', models.BigIntegerField(null=True)),
                ('protocolo', models.CharField(max_length=100, null=True)),
                ('idCanalPrestacao', models.IntegerField(null=True)),
                ('idCanalAvaliacao', models.IntegerField(null=True)),
                ('idPesquisa', models.IntegerField(null=True)),
                ('criado_em', models.DateTimeField(null=True)),
                ('respondido_em', models.DateTimeField(null=True)),
                ('nome', models.TextField(default='sem_nome')),
                ('telefone', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'Avaliacao',
            },
        ),
        migrations.CreateModel(
            name='CanalAvaliacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, null=True)),
                ('ativo', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'Canal_avalicao',
            },
        ),
        migrations.CreateModel(
            name='CanalPrestacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, null=True)),
                ('ativo', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'Canal_prestacao',
            },
        ),
        migrations.CreateModel(
            name='Opcoes',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('texto_opcao', models.TextField()),
                ('criado_em', models.DateTimeField(null=True)),
                ('atualizado_em', models.DateTimeField(null=True)),
                ('pergunta_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Opcoes',
            },
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idSEI', models.IntegerField(null=True)),
                ('nome', models.CharField(max_length=255, null=True)),
                ('nome_curto', models.CharField(max_length=255, null=True)),
                ('link', models.CharField(max_length=255, null=True)),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('ativo', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'Orgao',
            },
        ),
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto_pergunta', models.TextField()),
                ('tipo_pergunta', models.IntegerField(null=True)),
                ('criado_em', models.DateTimeField(null=True)),
                ('atualizado_em', models.DateTimeField(null=True)),
                ('survey_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Perguntas',
            },
        ),
        migrations.CreateModel(
            name='Pesquisas',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('orgao_id', models.IntegerField(null=True)),
                ('titulo', models.CharField(max_length=100, null=True)),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('criado_em', models.DateTimeField(null=True)),
                ('atualizado_em', models.DateTimeField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('is_active', models.BooleanField()),
                ('tipo_servico', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Pesquisas',
            },
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.BigIntegerField(null=True)),
                ('id_avaliacao', models.CharField(max_length=100, null=True)),
                ('survey_id', models.IntegerField(null=True)),
                ('question_id', models.IntegerField(null=True)),
                ('option_id', models.IntegerField(null=True)),
                ('texto_resposta', models.TextField()),
                ('criado_em', models.DateTimeField(null=True)),
                ('atualizado_em', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'Respostas',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idOrgao', models.IntegerField(null=True)),
                ('id_tipoService', models.IntegerField(null=True)),
                ('nome', models.CharField(max_length=255, null=True)),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('ativo', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'Servico',
            },
        ),
        migrations.CreateModel(
            name='TipoPergunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('ativo', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'Tipo_pergunta',
            },
        ),
        migrations.CreateModel(
            name='TipoService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, null=True)),
                ('ativo', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'TipoService',
            },
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=250)),
                ('user_group', models.IntegerField()),
                ('cpf', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'user_auth',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'user_groups',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('ddd', models.CharField(max_length=2, null=True)),
                ('telefone', models.CharField(max_length=9, null=True)),
                ('cargo', models.CharField(max_length=100, null=True)),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('orgao_id', models.IntegerField(null=True)),
                ('criado_em', models.DateTimeField(null=True)),
                ('atualizado_em', models.DateTimeField(null=True)),
                ('delete', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('webhook', models.TextField(null=True)),
                ('is_active', models.BooleanField(null=True)),
                ('atualizado_em', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'webhook',
            },
        ),
    ]
