# Generated by Django 4.2.2 on 2024-02-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUserOrgao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField()),
                ('id_orgao', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_orgao',
            },
        ),
        migrations.CreateModel(
            name='WebhookRuntime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('status_code', models.IntegerField()),
                ('date', models.DateTimeField(null=True)),
                ('runtime', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'webhook_runtime',
            },
        ),
        migrations.AlterField(
            model_name='pesquisas',
            name='tipo_servico',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
